apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: medisupply
data:
  # Configuraci贸n general
  FLASK_ENV: "production"
  PYTHONPATH: "/app"
  
  # URLs de servicios (para comunicaci贸n entre microservicios)
  USUARIOS_SERVICE_URL: "http://usuarios-service:5001/usuarios/api"
  PRODUCTOS_SERVICE_URL: "http://productos-service:5000/productos/api"
  LOGISTICA_SERVICE_URL: "http://logistica-service:5003/logistica/api"
  
  # Configuraci贸n de GCP
  GCP_PROJECT_ID: "desarrolloswcloud"
  GCP_BUCKET_NAME: "evidencias-g12"
  
  # Cloud SQL Proxy
  CLOUD_SQL_CONNECTION_NAME: "desarrolloswcloud:us-central1:medisupply-db-prod"
  
  # Configuraci贸n de base de datos
  DB_PORT: "5432"
  
  # Nombres de bases de datos
  USUARIOS_DB_NAME: "usuarios_db"
  PRODUCTOS_DB_NAME: "productos_db"
  VENTAS_DB_NAME: "ventas_db"
  LOGISTICA_DB_NAME: "logistica_db"
