apiVersion: apps/v1
kind: Deployment
metadata:
  name: logistica-deployment
  namespace: medisupply
  labels:
    app: logistica
spec:
  replicas: 2
  selector:
    matchLabels:
      app: logistica
  template:
    metadata:
      labels:
        app: logistica
    spec:
      containers:
      - name: logistica
        image: gcr.io/desarrolloswcloud/logistica:latest
        ports:
        - containerPort: 5003
        env:
        - name: FLASK_APP
          value: "src/main.py"
        - name: FLASK_ENV
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: FLASK_ENV
        - name: PYTHONPATH
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: PYTHONPATH
        - name: DB_HOST
          value: "10.74.0.9"  # IP privada de logistica-db
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: LOGISTICA_DB_NAME
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: logistica-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: logistica-password
        - name: SQLALCHEMY_DATABASE_URI
          value: "postgresql://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)"
        - name: GCP_PROJECT_ID
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: GCP_PROJECT_ID
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "500m"
      serviceAccountName: medisupply-ksa
---
apiVersion: v1
kind: Service
metadata:
  name: logistica-service
  namespace: medisupply
  labels:
    app: logistica
spec:
  selector:
    app: logistica
  ports:
  - port: 5003
    targetPort: 5003
  type: ClusterIP
