apiVersion: apps/v1
kind: Deployment
metadata:
  name: productos-deployment
  namespace: medisupply
  labels:
    app: productos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productos
  template:
    metadata:
      labels:
        app: productos
    spec:
      containers:
      - name: productos
        image: gcr.io/desarrolloswcloud/productos:latest
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_APP
          value: "src/main.py"
        - name: FLASK_ENV
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: FLASK_ENV
        - name: PYTHONPATH
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: PYTHONPATH
        - name: DB_HOST
          value: "localhost"  # Cloud SQL Proxy
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: PRODUCTOS_DB_NAME
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: productos-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: productos-password
        - name: SQLALCHEMY_DATABASE_URI
          value: "postgresql://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)"
        - name: USUARIOS_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: USUARIOS_SERVICE_URL
        - name: GCP_PROJECT_ID
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: GCP_PROJECT_ID
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "500m"
      # Cloud SQL Proxy sidecar
      - name: cloud-sql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.33.2
        command:
          - "/cloud_sql_proxy"
          - "-instances=$(CONNECTION_NAME)=tcp:5432"
        env:
        - name: CONNECTION_NAME
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: CLOUD_SQL_CONNECTION_NAME
        securityContext:
          runAsNonRoot: true
      serviceAccountName: medisupply-ksa
---
apiVersion: v1
kind: Service
metadata:
  name: productos-service
  namespace: medisupply
  labels:
    app: productos
  annotations:
    cloud.google.com/backend-config: '{"default": "medisupply-cors-config"}'
spec:
  selector:
    app: productos
  ports:
  - port: 5000
    targetPort: 5000
  type: ClusterIP
