name: Create Release Branch

on:
  workflow_dispatch:
    inputs:
      version_bump:
        description: 'Version bump type'
        required: true
        type: choice
        options:
          - patch  # 1.0.0 → 1.0.1
          - minor  # 1.0.0 → 1.1.0
          - major  # 1.0.0 → 2.0.0

permissions:
  contents: write
  pull-requests: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout develop
      uses: actions/checkout@v4
      with:
        ref: develop
        fetch-depth: 0
    
    - name: Configure Git
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
    
    - name: Calculate new version
      id: bump
      run: |
        CURRENT=$(cat VERSION)
        echo "Current version: $CURRENT"
        
        IFS='.' read -r -a parts <<< "$CURRENT"
        
        case "${{ inputs.version_bump }}" in
          major)
            NEW="$((parts[0]+1)).0.0"
            ;;
          minor)
            NEW="${parts[0]}.$((parts[1]+1)).0"
            ;;
          patch)
            NEW="${parts[0]}.${parts[1]}.$((parts[2]+1))"
            ;;
        esac
        
        echo "new_version=$NEW" >> $GITHUB_OUTPUT
        echo "New version: $NEW"
    
    - name: Create release branch
      run: |
        BRANCH="release/v${{ steps.bump.outputs.new_version }}"
        git checkout -b "$BRANCH"
        echo "${{ steps.bump.outputs.new_version }}" > VERSION
        git add VERSION
        git commit -m "chore: bump version to ${{ steps.bump.outputs.new_version }}"
        git push origin "$BRANCH"
        echo "branch_name=$BRANCH" >> $GITHUB_OUTPUT
      id: branch
    
    - name: Create Pull Request
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh pr create \
          --base main \
          --head "${{ steps.branch.outputs.branch_name }}" \
          --title "Release v${{ steps.bump.outputs.new_version }}" \
          --body "## Release v${{ steps.bump.outputs.new_version }}

        This PR contains the version bump from \`develop\` to prepare for release.

        ### Changes
        - Updated VERSION to ${{ steps.bump.outputs.new_version }}

        ### Checklist
        - [ ] All tests passing
        - [ ] Documentation updated
        - [ ] Ready for production deployment

        **After merge:** This will automatically deploy to production and create tag \`v${{ steps.bump.outputs.new_version }}\`"

